api_url: ''
extra_args:
  rstrip: '"'
model: gpt-3.5-turbo-1106
model_args: {}
prompt_template: |-
  Given the original text:
  """
  {data}
  """
  Generate a plain text summary of the text. Generate only the output summary without any additional comments.
start_with: |-
  Here is the summary:
  "
system_msg: You are an expert automatic summarization system.
type: openai_gen
