datasets:
  easy-vqa:
    class: base.HTMLDataset
    description: ''
    splits:
    - test
  logicnlg:
    class: logicnlg.LogicNLG
    description: Sample of 100 examples from the  <a href="https://github.com/wenhuchen/LogicNLG">LogicNLG</a>
      dataset.
    source: https://huggingface.co/datasets/kasnerz/logicnlg
    splits:
    - test
    outputs:
    - gpt4-direct-2shotcot
  quintd1-gsmarena:
    class: gsmarena.GSMArena
    description: <p>The <code>gsmarena</code> subset of the <a href="https://github.com/kasnerz/quintd/">quintd-1
      dataset</a>. </p><p>Contains mobile phone specifications from GSMArena.com.</p>
    source: https://github.com/kasnerz/quintd/tree/main/data/quintd-1
    splits:
    - dev
    - test
    outputs:
    - llama2
    - mistral
    - zephyr
    - gpt-3.5
  quintd1-ice_hockey:
    class: ice_hockey.IceHockey
    description: <p>The <code>ice_hockey</code> subset of the <a href="https://github.com/kasnerz/quintd/">quintd-1
      dataset</a>. </p><p>Contains ice hockey game summaries from <a href="https://rapidapi.com/fluis.lacasse/api/icehockeyapi">RapidAPI.com</a>.</p>
    splits:
    - dev
    - test
    source: https://github.com/kasnerz/quintd/tree/main/data/quintd-1
    splits:
    - dev
    - test
    outputs:
    - llama2
    - mistral
    - zephyr
    - gpt-3.5
  quintd1-openweather:
    class: openweather.OpenWeather
    description: <p>The <code>openweather</code> subset of the <a href="https://github.com/kasnerz/quintd/">quintd-1
      dataset</a>. </p><p>Contains weather forecasts from <a href="https://openweathermap.org/forecast5">OpenWeather</a>.</p>
    splits:
    - dev
    - test
    source: https://github.com/kasnerz/quintd/tree/main/data/quintd-1
    splits:
    - dev
    - test
    outputs:
    - llama2
    - mistral
    - zephyr
    - gpt-3.5
  quintd1-owid:
    class: owid.OurWorldInData
    description: <p>The <code>owid</code> subset of the <a href="https://github.com/kasnerz/quintd/">quintd-1
      dataset</a>. </p><p>Contains health-related time series from <a href="https://ourworldindata.org">Our
      World in Data</a>.</p>
    splits:
    - dev
    - test
    source: https://github.com/kasnerz/quintd/tree/main/data/quintd-1
    splits:
    - dev
    - test
    outputs:
    - llama2
    - mistral
    - zephyr
    - gpt-3.5
  quintd1-wikidata:
    class: wikidata.Wikidata
    description: <p>The <code>wikidata</code> subset of the <a href="https://github.com/kasnerz/quintd/">quintd-1
      dataset</a>. </p><p>Contains <a href="https://www.wikidata.org/wiki/Wikidata:Main_Page">wikidata</a>
      entities and their properties.</p>
    splits:
    - dev
    - test
    source: https://github.com/kasnerz/quintd/tree/main/data/quintd-1
    splits:
    - dev
    - test
    outputs:
    - llama2
    - mistral
    - zephyr
    - gpt-3.5
  xsum:
    class: base.PlainTextDataset
    description: Sample of 100 examples from the <a href="https://github.com/EdinburghNLP/XSum">XSum</a>
      dataset.
    splits:
    - test
  xsum-debug:
    class: base.PlainTextDataset
    description: ''
    splits:
    - test
