easy-vqa:
  class: basic.HTMLDataset
  description: A toy visual question answering dataset. Provided as an example dataset
    loaded by the <code>basic.HTMLDataset</code> class.
  enabled: false
  splits:
  - test
logicnlg-100:
  class: logicnlg.LogicNLG
  description: Sample of 100 examples from the  <a href="https://github.com/wenhuchen/LogicNLG">LogicNLG</a>
    dataset. Provided as an example dataset loaded from Huggingface, including post-processing
    with custom outputs.
  enabled: true
  splits:
  - test
quintd1-gsmarena:
  class: gsmarena.GSMArena
  description: '<p>The <code>gsmarena</code> subset of the <a href="https://github.com/kasnerz/quintd/">quintd-1
    dataset</a>.  Contains mobile phone specifications from GSMArena.com.</p><p><i>Note:
    annotations and GPT-3.5 outputs are available only for the test set.</i></p>'
  enabled: true
  splits:
  - dev
  - test
quintd1-ice_hockey:
  class: ice_hockey.IceHockey
  description: '<p>The <code>ice_hockey</code> subset of the <a href="https://github.com/kasnerz/quintd/">quintd-1
    dataset</a>.  Contains ice hockey game summaries from <a href="https://rapidapi.com/fluis.lacasse/api/icehockeyapi">RapidAPI.com</a>.</p><p><i>Note:
    annotations and GPT-3.5 outputs are available only for the test set.</i></p>'
  enabled: true
  splits:
  - dev
  - test
quintd1-openweather:
  class: openweather.OpenWeather
  description: '<p>The <code>openweather</code> subset of the <a href="https://github.com/kasnerz/quintd/">quintd-1
    dataset</a>.  Contains weather forecasts from <a href="https://openweathermap.org/forecast5">OpenWeather</a>.</p><p><i>Note:
    annotations and GPT-3.5 outputs are available only for the test set.</i></p>'
  enabled: true
  splits:
  - dev
  - test
quintd1-owid:
  class: owid.OurWorldInData
  description: '<p>The <code>owid</code> subset of the <a href="https://github.com/kasnerz/quintd/">quintd-1
    dataset</a>.  Contains health-related time series from <a href="https://ourworldindata.org">Our
    World in Data</a>. <p><i>Note: annotations and GPT-3.5 outputs are available only
    for the test set.</i></p>'
  enabled: true
  splits:
  - dev
  - test
quintd1-wikidata:
  class: wikidata.Wikidata
  description: '<p>The <code>wikidata</code> subset of the <a href="https://github.com/kasnerz/quintd/">quintd-1
    dataset</a>.  Contains <a href="https://www.wikidata.org/wiki/Wikidata:Main_Page">wikidata</a>
    entities and their properties.</p><p><i>Note: annotations and GPT-3.5 outputs
    are available only for the test set.</i></p>'
  enabled: true
  splits:
  - dev
  - test
rotowire-shared-task:
  class: rotowire_shared_task.RotowireSharedTask
  description: ''
  enabled: true
  splits:
  - test
xsum-debug:
  class: basic.PlainTextDataset
  description: Sample of 5 examples from the <a href="https://github.com/EdinburghNLP/XSum">XSum</a>
    dataset.
  enabled: true
  splits:
  - test
