annotation_span_categories:
  - name: "Incorrect"
    color: "#ffbcbc"
  - name: "Not checkable"
    color: "#e9d2ff"
  - name: "Misleading"
    color: "#fff79f"
  - name: "Other"
    color: "#bbbbbb"
examples_per_batch: 10
# options:
# - `dataset-level`: shuffles all outputs in the dataset
# - `example-level`: shuffles outputs for each example keeping the order of examples
sort_order: dataset-level
# time after which an unfinished example can be re-assigned to a new annotator (minutes)
idle_time: 120
completion_code: "ABCDE"
