---
allow_annotate: true
allow_browse: true
debug: true
host_prefix: "/namuddis/factgenie"
default_error_categories:
  - name: "Incorrect"
    color: "#ffbcbc"
  - name: "Not checkable"
    color: "#e9d2ff"
  - name: "Misleading"
    color: "#fff79f"
  - name: "Other"
    color: "#bbbbbb"
logging_level: "INFO"
