type: ollama
model: llama3
api_url: http://tdll-3gpu3.ufal.hide.ms.mff.cuni.cz:11434/api/generate
model_args:
  max_tokens: 1024
  num_beams: 1
  temperature: 0.0
  top_p: 1.0
  top_k: 0.0
  do_sample: false 
  seed: 42
system_msg: "You are an expert data-to-text system. You undestand structured data and you can correcly operate with units and numerical values. You are designed to output plain text summaries from structured data input."
annotation_span_categories:
  - name: "Incorrect"
    color: "#ffbcbc"
  - name: "Not checkable"
    color: "#e9d2ff"
  - name: "Misleading"
    color: "#fff79f"
  - name: "Other"
    color: "#bbbbbb"
prompt_template: |
  Given the data:
  ```
  {data}
  ```
  Generate a summary in plain text, describing facts and values contained in the input:

  *Example:*
  data:
  ```
  Nokia 3310
  -----
  - **color**: black, blue, grey
  - **display**: 320x240px
  ```
  output (product description):
  ```
  Nokia 3310 features a 320x240 display. It is available in black, blue and grey color. The data seem to provide only partial information about the phone.
  ```
  Do not add or fabricate any detail not reflected in the data. Also do not be too strict: some facts can be less specific than in the data (rounded values, shortened or abbreviated text, etc.).
